package com.lxt.ms.push.model;

import java.util.Date;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.PROCESS_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.PROCESS_CATEGORY_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String processCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.NAME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.PROCESS_KEY
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String processKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.VERSION_NO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.MEMO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.PUBLISH_STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.PUBLISH_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.INSERT_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.INSERT_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.UPDATE_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process.DEPLOYE_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    private String deployeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.PROCESS_ID
     *
     * @return the value of lxt_process.PROCESS_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.PROCESS_ID
     *
     * @param processId the value for lxt_process.PROCESS_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.PROCESS_CATEGORY_ID
     *
     * @return the value of lxt_process.PROCESS_CATEGORY_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getProcessCategoryId() {
        return processCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.PROCESS_CATEGORY_ID
     *
     * @param processCategoryId the value for lxt_process.PROCESS_CATEGORY_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setProcessCategoryId(String processCategoryId) {
        this.processCategoryId = processCategoryId == null ? null : processCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.NAME
     *
     * @return the value of lxt_process.NAME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.NAME
     *
     * @param name the value for lxt_process.NAME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.PROCESS_KEY
     *
     * @return the value of lxt_process.PROCESS_KEY
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getProcessKey() {
        return processKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.PROCESS_KEY
     *
     * @param processKey the value for lxt_process.PROCESS_KEY
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setProcessKey(String processKey) {
        this.processKey = processKey == null ? null : processKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.VERSION_NO
     *
     * @return the value of lxt_process.VERSION_NO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.VERSION_NO
     *
     * @param versionNo the value for lxt_process.VERSION_NO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo == null ? null : versionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.MEMO
     *
     * @return the value of lxt_process.MEMO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.MEMO
     *
     * @param memo the value for lxt_process.MEMO
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.STATUS
     *
     * @return the value of lxt_process.STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.STATUS
     *
     * @param status the value for lxt_process.STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.PUBLISH_STATUS
     *
     * @return the value of lxt_process.PUBLISH_STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.PUBLISH_STATUS
     *
     * @param publishStatus the value for lxt_process.PUBLISH_STATUS
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.PUBLISH_TIME
     *
     * @return the value of lxt_process.PUBLISH_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.PUBLISH_TIME
     *
     * @param publishTime the value for lxt_process.PUBLISH_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.INSERT_USER_ID
     *
     * @return the value of lxt_process.INSERT_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.INSERT_USER_ID
     *
     * @param insertUserId the value for lxt_process.INSERT_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.INSERT_TIME
     *
     * @return the value of lxt_process.INSERT_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.INSERT_TIME
     *
     * @param insertTime the value for lxt_process.INSERT_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.UPDATE_USER_ID
     *
     * @return the value of lxt_process.UPDATE_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.UPDATE_USER_ID
     *
     * @param updateUserId the value for lxt_process.UPDATE_USER_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.UPDATE_TIME
     *
     * @return the value of lxt_process.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.UPDATE_TIME
     *
     * @param updateTime the value for lxt_process.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process.DEPLOYE_ID
     *
     * @return the value of lxt_process.DEPLOYE_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public String getDeployeId() {
        return deployeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process.DEPLOYE_ID
     *
     * @param deployeId the value for lxt_process.DEPLOYE_ID
     *
     * @mbggenerated Thu Apr 04 15:26:54 CST 2019
     */
    public void setDeployeId(String deployeId) {
        this.deployeId = deployeId == null ? null : deployeId.trim();
    }
}