package com.lxt.ms.chat.mapper;

import com.lxt.ms.chat.model.ChatFriendCategory;
import com.lxt.ms.chat.model.ChatFriendCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatFriendCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int countByExample(ChatFriendCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int deleteByExample(ChatFriendCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int deleteByPrimaryKey(String friendCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int insert(ChatFriendCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int insertSelective(ChatFriendCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    List<ChatFriendCategory> selectByExample(ChatFriendCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    ChatFriendCategory selectByPrimaryKey(String friendCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") ChatFriendCategory record, @Param("example") ChatFriendCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int updateByExample(@Param("record") ChatFriendCategory record, @Param("example") ChatFriendCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int updateByPrimaryKeySelective(ChatFriendCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_friend_category
     *
     * @mbggenerated Wed Oct 10 13:27:53 CST 2018
     */
    int updateByPrimaryKey(ChatFriendCategory record);
}