package com.lxt.chenjia.manage.model;

public class UserSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.USER_ID
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.NICK_NAME
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.CHAT_MOOD
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private String chatMood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.CHAT_STATUS
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private Integer chatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.HEAD_PIC
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_user_setting.MENU_CONFIG
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    private String menuConfig;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.USER_ID
     *
     * @return the value of lxt_user_setting.USER_ID
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.USER_ID
     *
     * @param userId the value for lxt_user_setting.USER_ID
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.NICK_NAME
     *
     * @return the value of lxt_user_setting.NICK_NAME
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.NICK_NAME
     *
     * @param nickName the value for lxt_user_setting.NICK_NAME
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.CHAT_MOOD
     *
     * @return the value of lxt_user_setting.CHAT_MOOD
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public String getChatMood() {
        return chatMood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.CHAT_MOOD
     *
     * @param chatMood the value for lxt_user_setting.CHAT_MOOD
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setChatMood(String chatMood) {
        this.chatMood = chatMood == null ? null : chatMood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.CHAT_STATUS
     *
     * @return the value of lxt_user_setting.CHAT_STATUS
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public Integer getChatStatus() {
        return chatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.CHAT_STATUS
     *
     * @param chatStatus the value for lxt_user_setting.CHAT_STATUS
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setChatStatus(Integer chatStatus) {
        this.chatStatus = chatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.HEAD_PIC
     *
     * @return the value of lxt_user_setting.HEAD_PIC
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.HEAD_PIC
     *
     * @param headPic the value for lxt_user_setting.HEAD_PIC
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_user_setting.MENU_CONFIG
     *
     * @return the value of lxt_user_setting.MENU_CONFIG
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public String getMenuConfig() {
        return menuConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_user_setting.MENU_CONFIG
     *
     * @param menuConfig the value for lxt_user_setting.MENU_CONFIG
     *
     * @mbggenerated Tue May 29 15:15:22 CST 2018
     */
    public void setMenuConfig(String menuConfig) {
        this.menuConfig = menuConfig == null ? null : menuConfig.trim();
    }
}