package com.lxt.ms.workflow.model;

import java.util.Date;

public class PageComponent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.COMPONENT_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String componentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.PAGE_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.LABEL
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.COMPONENT
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.MEMO
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.INSERT_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.USER_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.MSG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.REGEX
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String regex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.REQUIRED
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.MIN_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private Integer minLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.MAX_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private Integer maxLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.DEFAULT_VALUE
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String defaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.PRIORITY
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page_component.CONFIG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    private String config;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.COMPONENT_ID
     *
     * @return the value of lxt_page_component.COMPONENT_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.COMPONENT_ID
     *
     * @param componentId the value for lxt_page_component.COMPONENT_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setComponentId(String componentId) {
        this.componentId = componentId == null ? null : componentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.PAGE_ID
     *
     * @return the value of lxt_page_component.PAGE_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.PAGE_ID
     *
     * @param pageId the value for lxt_page_component.PAGE_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setPageId(String pageId) {
        this.pageId = pageId == null ? null : pageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.LABEL
     *
     * @return the value of lxt_page_component.LABEL
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.LABEL
     *
     * @param label the value for lxt_page_component.LABEL
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.COMPONENT
     *
     * @return the value of lxt_page_component.COMPONENT
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.COMPONENT
     *
     * @param component the value for lxt_page_component.COMPONENT
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.MEMO
     *
     * @return the value of lxt_page_component.MEMO
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.MEMO
     *
     * @param memo the value for lxt_page_component.MEMO
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.INSERT_TIME
     *
     * @return the value of lxt_page_component.INSERT_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.INSERT_TIME
     *
     * @param insertTime the value for lxt_page_component.INSERT_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.UPDATE_TIME
     *
     * @return the value of lxt_page_component.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.UPDATE_TIME
     *
     * @param updateTime the value for lxt_page_component.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.USER_ID
     *
     * @return the value of lxt_page_component.USER_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.USER_ID
     *
     * @param userId the value for lxt_page_component.USER_ID
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.MSG
     *
     * @return the value of lxt_page_component.MSG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.MSG
     *
     * @param msg the value for lxt_page_component.MSG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.REGEX
     *
     * @return the value of lxt_page_component.REGEX
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getRegex() {
        return regex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.REGEX
     *
     * @param regex the value for lxt_page_component.REGEX
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setRegex(String regex) {
        this.regex = regex == null ? null : regex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.REQUIRED
     *
     * @return the value of lxt_page_component.REQUIRED
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.REQUIRED
     *
     * @param required the value for lxt_page_component.REQUIRED
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setRequired(String required) {
        this.required = required == null ? null : required.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.MIN_LENGTH
     *
     * @return the value of lxt_page_component.MIN_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public Integer getMinLength() {
        return minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.MIN_LENGTH
     *
     * @param minLength the value for lxt_page_component.MIN_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.MAX_LENGTH
     *
     * @return the value of lxt_page_component.MAX_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public Integer getMaxLength() {
        return maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.MAX_LENGTH
     *
     * @param maxLength the value for lxt_page_component.MAX_LENGTH
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.DEFAULT_VALUE
     *
     * @return the value of lxt_page_component.DEFAULT_VALUE
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.DEFAULT_VALUE
     *
     * @param defaultValue the value for lxt_page_component.DEFAULT_VALUE
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.PRIORITY
     *
     * @return the value of lxt_page_component.PRIORITY
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.PRIORITY
     *
     * @param priority the value for lxt_page_component.PRIORITY
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page_component.CONFIG
     *
     * @return the value of lxt_page_component.CONFIG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page_component.CONFIG
     *
     * @param config the value for lxt_page_component.CONFIG
     *
     * @mbggenerated Thu Feb 14 11:30:52 CST 2019
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }
}