package com.lxt.ms.workflow.model;

import java.util.Date;

public class Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.CATEGORY
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.PLATFORM
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.NAME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.MEMO
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.STATUS
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.INSERT_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.USER_ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_page.URL
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.ID
     *
     * @return the value of lxt_page.ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.ID
     *
     * @param id the value for lxt_page.ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.CATEGORY
     *
     * @return the value of lxt_page.CATEGORY
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.CATEGORY
     *
     * @param category the value for lxt_page.CATEGORY
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.PLATFORM
     *
     * @return the value of lxt_page.PLATFORM
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.PLATFORM
     *
     * @param platform the value for lxt_page.PLATFORM
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.NAME
     *
     * @return the value of lxt_page.NAME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.NAME
     *
     * @param name the value for lxt_page.NAME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.MEMO
     *
     * @return the value of lxt_page.MEMO
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.MEMO
     *
     * @param memo the value for lxt_page.MEMO
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.STATUS
     *
     * @return the value of lxt_page.STATUS
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.STATUS
     *
     * @param status the value for lxt_page.STATUS
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.INSERT_TIME
     *
     * @return the value of lxt_page.INSERT_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.INSERT_TIME
     *
     * @param insertTime the value for lxt_page.INSERT_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.UPDATE_TIME
     *
     * @return the value of lxt_page.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.UPDATE_TIME
     *
     * @param updateTime the value for lxt_page.UPDATE_TIME
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.USER_ID
     *
     * @return the value of lxt_page.USER_ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.USER_ID
     *
     * @param userId the value for lxt_page.USER_ID
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_page.URL
     *
     * @return the value of lxt_page.URL
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_page.URL
     *
     * @param url the value for lxt_page.URL
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}