package com.lxt.ms.workflow.model;

import java.util.Date;

public class Rule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.category
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.name
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.version
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.insert_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.update_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.user_id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.memo
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_rule.content
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.id
     *
     * @return the value of lxt_rule.id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.id
     *
     * @param id the value for lxt_rule.id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.category
     *
     * @return the value of lxt_rule.category
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.category
     *
     * @param category the value for lxt_rule.category
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.name
     *
     * @return the value of lxt_rule.name
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.name
     *
     * @param name the value for lxt_rule.name
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.version
     *
     * @return the value of lxt_rule.version
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.version
     *
     * @param version the value for lxt_rule.version
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.insert_time
     *
     * @return the value of lxt_rule.insert_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.insert_time
     *
     * @param insertTime the value for lxt_rule.insert_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.update_time
     *
     * @return the value of lxt_rule.update_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.update_time
     *
     * @param updateTime the value for lxt_rule.update_time
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.user_id
     *
     * @return the value of lxt_rule.user_id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.user_id
     *
     * @param userId the value for lxt_rule.user_id
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.memo
     *
     * @return the value of lxt_rule.memo
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.memo
     *
     * @param memo the value for lxt_rule.memo
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_rule.content
     *
     * @return the value of lxt_rule.content
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_rule.content
     *
     * @param content the value for lxt_rule.content
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}