package com.lxt.ms.manage.mapper;

import com.lxt.ms.manage.model.Dictionary;
import com.lxt.ms.manage.model.DictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int countByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int deleteByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    List<Dictionary> selectByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int updateByExample(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_dictionary
     *
     * @mbggenerated Tue Nov 13 10:48:01 CST 2018
     */
    int updateByPrimaryKey(Dictionary record);
}