package com.lxt.ms.manage.mapper;

import com.lxt.ms.manage.model.Feedback;
import com.lxt.ms.manage.model.FeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int countByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int deleteByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    Feedback selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByExample(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_feedback
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByPrimaryKey(Feedback record);
}