package com.lxt.ms.manage.mapper;

import com.lxt.ms.manage.model.Menu;
import com.lxt.ms.manage.model.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    Menu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_menu
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    int updateByPrimaryKey(Menu record);
}