package com.lxt.ms.manage.mapper;

import com.lxt.ms.manage.model.UserSetting;
import com.lxt.ms.manage.model.UserSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int countByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int deleteByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int insert(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int insertSelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    List<UserSetting> selectByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    UserSetting selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByExample(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByPrimaryKeySelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user_setting
     *
     * @mbggenerated Wed May 22 11:23:04 CST 2019
     */
    int updateByPrimaryKey(UserSetting record);
}