package com.lxt.ms.manage.model;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.CATEGORY
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.PLATFORM
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.TITLE
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.CONTENT
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.INSERT_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.UPDATE_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.USER_ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_feedback.STATUS
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.ID
     *
     * @return the value of lxt_feedback.ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.ID
     *
     * @param id the value for lxt_feedback.ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.CATEGORY
     *
     * @return the value of lxt_feedback.CATEGORY
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.CATEGORY
     *
     * @param category the value for lxt_feedback.CATEGORY
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.PLATFORM
     *
     * @return the value of lxt_feedback.PLATFORM
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.PLATFORM
     *
     * @param platform the value for lxt_feedback.PLATFORM
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.TITLE
     *
     * @return the value of lxt_feedback.TITLE
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.TITLE
     *
     * @param title the value for lxt_feedback.TITLE
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.CONTENT
     *
     * @return the value of lxt_feedback.CONTENT
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.CONTENT
     *
     * @param content the value for lxt_feedback.CONTENT
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.INSERT_TIME
     *
     * @return the value of lxt_feedback.INSERT_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.INSERT_TIME
     *
     * @param insertTime the value for lxt_feedback.INSERT_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.UPDATE_TIME
     *
     * @return the value of lxt_feedback.UPDATE_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.UPDATE_TIME
     *
     * @param updateTime the value for lxt_feedback.UPDATE_TIME
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.USER_ID
     *
     * @return the value of lxt_feedback.USER_ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.USER_ID
     *
     * @param userId the value for lxt_feedback.USER_ID
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_feedback.STATUS
     *
     * @return the value of lxt_feedback.STATUS
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_feedback.STATUS
     *
     * @param status the value for lxt_feedback.STATUS
     *
     * @mbggenerated Fri Feb 22 15:49:44 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}