package com.lxt.ms.manage.model;

public class ProcessCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process_category.ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process_category.PARENT_ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process_category.NAME
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxt_process_category.MEMO
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process_category.ID
     *
     * @return the value of lxt_process_category.ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process_category.ID
     *
     * @param id the value for lxt_process_category.ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process_category.PARENT_ID
     *
     * @return the value of lxt_process_category.PARENT_ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process_category.PARENT_ID
     *
     * @param parentId the value for lxt_process_category.PARENT_ID
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process_category.NAME
     *
     * @return the value of lxt_process_category.NAME
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process_category.NAME
     *
     * @param name the value for lxt_process_category.NAME
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxt_process_category.MEMO
     *
     * @return the value of lxt_process_category.MEMO
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxt_process_category.MEMO
     *
     * @param memo the value for lxt_process_category.MEMO
     *
     * @mbggenerated Wed May 22 10:56:10 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}