package com.lxt.ms.push.mapper;

import com.lxt.ms.push.model.User;
import com.lxt.ms.push.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_user
     *
     * @mbggenerated Thu Apr 04 15:26:55 CST 2019
     */
    int updateByPrimaryKey(User record);
}