package com.lxt.ms.workflow.mapper;

import com.lxt.ms.workflow.model.ChatRecord;
import com.lxt.ms.workflow.model.ChatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int countByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insertSelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    List<ChatRecord> selectByExample(ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    ChatRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExample(@Param("record") ChatRecord record, @Param("example") ChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKeySelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_chat_record
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKey(ChatRecord record);
}