package com.lxt.ms.workflow.mapper;

import com.lxt.ms.workflow.model.Regex;
import com.lxt.ms.workflow.model.RegexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int countByExample(RegexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByExample(RegexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insert(Regex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insertSelective(Regex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    List<Regex> selectByExample(RegexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    Regex selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Regex record, @Param("example") RegexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExample(@Param("record") Regex record, @Param("example") RegexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKeySelective(Regex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_regex
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKey(Regex record);
}