package com.lxt.ms.workflow.mapper;

import com.lxt.ms.workflow.model.Rule;
import com.lxt.ms.workflow.model.RuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int countByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insert(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int insertSelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    List<Rule> selectByExampleWithBLOBs(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    List<Rule> selectByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    Rule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByExample(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKeySelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxt_rule
     *
     * @mbggenerated Wed Mar 20 17:24:04 CST 2019
     */
    int updateByPrimaryKey(Rule record);
}